//General actions


export const LOOK_UP_SYMPTOM = 'LOOK_UP_SYMPTOM';
export const LOOK_UP_SYMPTOM_ERROR = 'LOOK_UP_SYMPTOM_ERROR';

//Actions related to booking consultations
export const CANCELLED_CONSULTATION = 'CANCELLED_CONSULTATION';
export const DECLINED_CONSULTATION = 'DECLINED_CONSULTATION';
export const ACCEPTED_CONSULTATION = 'ACCEPTED_CONSULTATION';
export const CONSULTATION_SUCCESS = 'CONSULTATION_SUCCESS';
export const CONSULTATION_ERROR = 'CONSULTATION_ERROR';
export const CONSULTATION_LOADING = 'CONSULTATION_LOADING';
export const TIME_ELAPSED_CONSULTATION = 'TIME_ELAPSED_CONSULTATION';

//Notifications
export const NOTIFICATIONS_COUNT = 'NOTIFICATIONS_COUNT';

//Cart actions
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INCREASE_ITEM = 'INCREASE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
